os: linux
sudo: required
language: python
cache: pip3

python:
  - 3.9

before_install:
  - pip install poetry

install:
  - poetry install --no-root -v
services:
- postgresql
env:
    - DB_DRIVER=postgresql DB_HOST=localhost DB_PORT=5432 DB_USER=postgres DB_PASSWORD=""
script: pytest
script:
  - python -m pytest -v tests/domain
